SeeAndYouGo/SeeAndYouGo-2

- frontend/src/App.js
- frontend/src/components/LoginPage/KakaoCallBack.js
- frontend/src/components/SideBar.js
- frontend/src/pages/LoginPage.js
- 로그인 성공 시 local storage에 저장된 nickname을 통해 닉네임 표기 및 로그아웃 버튼 활성화
- 로그아웃 시 local storage에 저장된 정보 모두 삭제
- 카카오 로그인 동작 중 백엔드에서 받은 결과에 따라 다른 동작 구현(새로운 유저, 등록된 유저 판단)
> 12 feat login status

- backend/bin/main/console-appender.xml
- backend/src/main/resources/console-appender.xml
- backend/src/main/resources/file-error-appender.xml
- backend/src/main/resources/file-info-appender.xml
- backend/src/main/resources/logback-spring.xml
* 일반적인 쿼리문과 같은 로그는 log/info에 저장
* 에러 로그는 log/error에 저장.
> feat: logging

- backend/src/main/java/com/SeeAndYouGo/SeeAndYouGo/Dish/Dish.java
- backend/src/main/java/com/SeeAndYouGo/SeeAndYouGo/Dish/DishController.java
- backend/src/main/java/com/SeeAndYouGo/SeeAndYouGo/Dish/DishDto.java
- backend/src/main/java/com/SeeAndYouGo/SeeAndYouGo/Dish/DishRepository.java
- backend/src/main/java/com/SeeAndYouGo/SeeAndYouGo/Dish/DishService.java
- backend/src/main/java/com/SeeAndYouGo/SeeAndYouGo/Menu/Menu.java
- backend/src/main/java/com/SeeAndYouGo/SeeAndYouGo/Menu/MenuService.java
- backend/src/main/java/com/SeeAndYouGo/SeeAndYouGo/Restaurant/RestaurantService.java
dish 및 menu 테이블의 중복(불필요) 컬럼들에 대한 수정 완료
dish 테이블에 id, name, dishType만 남겨두고, 
관련된 코드를 수정완료했습니다.
Closed #24
> fix: dish table

- frontend/Dockerfile
- frontend/package-lock.json
- frontend/package.json
- frontend/src/App.js
- frontend/src/components/MyReviewPage/MyReviewItem.js
- frontend/src/components/SideBar.js
- frontend/src/pages/MyReviewPage.js
- frontend/yarn.lock
- 내가 작성한 리뷰 기능 구현
- 사이드바 재구성 & 로그인 없이 member contents 이용 불가
> feat: my review

- frontend/src/components/DropDown.js
- frontend/src/components/RestaurantDetailPage/TopReview.js
- frontend/src/components/ReviewDelete.js
- frontend/src/components/ReviewPage/ReviewItem.js
- frontend/src/components/ReviewReport.js
- frontend/src/hooks/useDetectClose.js
- 리뷰에 신고하기 버튼을 드롭다운 버튼으로 변경
[before] 리뷰에 신고하기 버튼
[after] 드롭다운 메뉴(삭제하기, 신고하기) 버튼
- 탑 리뷰에도 드롭다운 버튼 적용
> 32 feat dropdown

- frontend/public/assets/json/weeklyMenu.json
- frontend/src/pages/AdminMainMenu.js
> refactor: Admin Main Menu

- frontend/src/App.js
- frontend/src/RouteChangeTracker.js
- frontend/src/index.js
- frontend/yarn.lock
> feat: Google Analytics

- frontend/Dockerfile
- frontend/src/App.js
- frontend/src/RouteChangeTracker.js
- frontend/src/index.js
- frontend/yarn.lock
dockerfile에 google analytics 추가
> 46 feat google analytics

- frontend/public/assets/json/weeklyMenu.json
- frontend/src/pages/AdminMainMenu.js
- 메인 메뉴 선정 부분 백엔드로 데이터 전송하는 구조 변경
- 관리자 페이지 접속을 위한 비밀번호 설정
> 40 refactor admin main menu

- frontend/src/components/ReviewPage/ModalImageZoom.js
- frontend/src/components/ReviewPage/ReviewItem.js
> feat: Review Image Zoom

- frontend/src/pages/RestaurantDetailPage/ReviewWrite.js
> feat: limitation review writing

- frontend/src/pages/RestaurantDetailPage/ReviewWrite.js
- 백엔드에게 전달되는 기존 데이터에 "anonymous"  속성 하나 추가
- true인 경우 익명, false인 경우 사용자의 닉네임 그대로 사용
> refactor: review write

- frontend/src/components/Review/ReviewDelete.js
- frontend/src/components/Review/ReviewReport.js
- frontend/src/components/SideBar.js
- frontend/src/components/Toast.js
- frontend/src/pages/LoginPage/KakaoCallBack.js
- frontend/src/pages/MainPage/MainPage.js
- frontend/src/pages/MyKeywordPage/MyKeywordInput.js
- frontend/src/pages/MyKeywordPage/MyKeywordItem.js
- frontend/src/pages/MyKeywordPage/MyKeywordPage.js
- frontend/src/pages/MyReviewPage/MyReviewItem.js
- frontend/src/pages/MyReviewPage/MyReviewPage.js
- frontend/src/pages/RestaurantDetailPage/RestaurantDetailPage.js
- frontend/src/pages/RestaurantDetailPage/ReviewWrite.js
- frontend/src/pages/ReviewPage/ReviewPage.js
- frontend/src/pages/SetNicknamePage/SetNicknamePage.js
- frontend/src/redux/slice/ToastSlice.js
- frontend/src/redux/store.js
- 토스트 메시지 구조 변경
- alert창 최대한 토스트 메시지로 변경(아직 반영 안 된 부분도 있음)
> refactor: toast message with redux-toolkit

- frontend/src/pages/RestaurantDetailPage/Menu.js
키워드가 포함된 메뉴 표기 방식 변경 (underline)
> refactor: menu display contain keywords

- frontend/Dockerfile
- frontend/package.json
- frontend/src/components/Loading.js
- frontend/src/components/Toast.js
- frontend/src/pages/LoginPage/KakaoCallBack.js
- frontend/src/pages/MyKeywordPage/MyKeywordPage.js
- frontend/src/pages/MyReviewPage/MyReviewPage.js
- frontend/yarn.lock
- 로그인 안 된 경우, 로그인이 필요한 컨텐츠 안 보이도록
- 로그인 안 된 경우, 기본적으로 sidebar 눌렀을 때 toast 표시
- 강제적으로 페이지에 접근한다면 "로그인이 필요합니다" 표시
- 로그인 기다리는 부분 loading component 추가해서 변경 (환경 변수 추가 필요)
- toast의 width를 늘려 문장이 애매하게 나눠지지 않도록 변경 (mobile 버전으로 확인했을 때 이상하게 보인 상황)
> fix access restrictions

- frontend/src/pages/RestaurantDetailPage/ReviewWrite.js
- 주말동안 리뷰 작성 불가
- 요일을 확인해 토요일, 일요일 인 경우 리뷰 작성 불가능하도록
- 클라우드에서 서버 실행하면 utc 시간이 기준으로 되기 때문에 9시간 더해줘 한국 시간으로 판단
> feat: review write restriction

- frontend/src/pages/RestaurantDetailPage/ReviewWrite.js
리뷰 작성하는 곳에서 주말인지 판단하는 곳 클라우드 시간과 상관 없게 수정
> 136 feat review write restrictions

- frontend/src/pages/RestaurantDetailPage/TopReview.js
- frontend/src/pages/ReviewPage/ReviewItem.js
> fix: review item

- frontend/src/pages/MainPage/Cafeteria.js
- frontend/src/pages/RestaurantDetailPage/MenuInfoForRestaurant1.js
- frontend/src/pages/RestaurantDetailPage/MenuInfoWith1Dept.js
- frontend/src/pages/RestaurantDetailPage/MenuInfoWith2Dept.js
- frontend/src/pages/ReviewPage/ReviewSelect.js
- API 요청시 token이 유효하지 않은 경우 처리하기
- 백엔드에게 API 요청할 때 들어가는 token이 유효하지 않을 때 error를 응답받았을 때
로그아웃 동작을 시켜, local storage에 저장되어 있는 값을 지우고, 현재 페이지를 새로고침 시킨다.
- 새로고침 된 결과, token이 없게 되기 때문에, token이 들어가지 않는 API를 다시 요청하게 된다.
- 일단 메인 페이지, 식당 상세 페이지, 리뷰 페이지만 적용된 상태
> fix: unavailable token

- frontend/src/components/Footer.js
- frontend/src/pages/MainPage/Cafeteria.js
- frontend/src/pages/RestaurantDetailPage/ReviewWrite.js
- frontend/src/pages/ReviewPage/ReviewSelect.js
리뷰 작성 시 2초후 새로고침하도록 수정
- 리뷰 작성 버튼 누르면 작성한 내용이 그대로 남아 있어 이 부분은 수정이 필요하다 생각
- 토스트 메시지를 모두 보여주기 위해 2초 후에 새로고침 하는 방향으로 수정
> 172 fix review write initialization

- frontend/src/pages/ReviewPage/ReviewItem.js
- 리뷰 공감 부분 위치 수정
- 리뷰 comment가 길어지는 경우, comment와 공감이 겹치는 문제 발생
- 메뉴와 곰감이 따로 한 줄을 차지할 수 있도록 위치 수정
> design: review like position

- frontend/src/pages/MyKeywordPage/MyKeywordInput.js
- frontend/src/pages/MyKeywordPage/MyKeywordItem.js
- frontend/src/pages/MyKeywordPage/MyKeywordPage.js
- frontend/src/pages/NoticePage/NoticePage.js
> 183 feat responsive web

- backend/src/main/java/com/SeeAndYouGo/SeeAndYouGo/Keyword/KeywordNotFoundException.java
- backend/src/main/java/com/SeeAndYouGo/SeeAndYouGo/Keyword/KeywordService.java
- backend/src/main/java/com/SeeAndYouGo/SeeAndYouGo/Menu/MenuService.java
- backend/src/main/java/com/SeeAndYouGo/SeeAndYouGo/OAuth/jwt/JwtFilter.java
https://splendidlolli.tistory.com/726
> refactor: do not return null

- backend/src/main/java/com/SeeAndYouGo/SeeAndYouGo/Menu/MenuController.java
- backend/src/main/java/com/SeeAndYouGo/SeeAndYouGo/Menu/MenuResponseDto.java
- backend/src/main/java/com/SeeAndYouGo/SeeAndYouGo/Menu/dto/MenuResponseByAdminDto.java
- backend/src/main/java/com/SeeAndYouGo/SeeAndYouGo/Menu/dto/MenuResponseByUserDto.java
- backend/src/main/java/com/SeeAndYouGo/SeeAndYouGo/Menu/dto/MenuResponseDto.java
> fix: weekly menu api

- frontend/src/pages/RestaurantDetailPage/DetailHeader.js
- frontend/src/pages/RestaurantDetailPage/MenuInfoWith2Dept.js
- frontend/src/pages/RestaurantDetailPage/MenuItem.js
- frontend/src/pages/RestaurantDetailPage/RestaurantDetailPage.js
- frontend/src/pages/RestaurantDetailPage/TopReviewItem.js
식당 상세 페이지 반응형 적용
- 2학, 3학의 경우 "교직원은 학생도 이용가능합니다" 라는 문구 때문에 화면 비율 맞추기가 어려워
일단은 왼쪽 화면의 min-width를 정해놓은 상태인데 회의때 보고 수정이 필요할 수도..
- 3학 학생식당의 price 부분은 "메뉴별 가격 상이"라고 표시
> feat: detail page responsive

- backend/src/main/java/com/SeeAndYouGo/SeeAndYouGo/user/User.java
- backend/src/main/java/com/SeeAndYouGo/SeeAndYouGo/user/UserController.java
- backend/src/main/java/com/SeeAndYouGo/SeeAndYouGo/user/UserService.java
- backend/src/main/java/com/SeeAndYouGo/SeeAndYouGo/user/dto/NicknameUpdateResponseDto.java
- frontend/src/components/SideBar.js
- frontend/src/pages/SetNicknamePage/SetNicknamePage.js
> feat: change nickname

- frontend/src/components/InfoModal.js
- frontend/src/components/SideBar.js
- frontend/src/pages/MainPage/MainPage.js
- 이벤트 탭 추가
- 서버 문제로 인한 서비스 중단 사과문 모달 추가
> feat: seeandyougo event

- frontend/public/assets/json/statistics/restaurant1.json
- frontend/public/assets/json/statistics/restaurant2.json
- frontend/public/assets/json/statistics/restaurant3.json
- frontend/public/assets/json/statistics/restaurant4.json
- frontend/public/assets/json/statistics/restaurant5.json
- frontend/src/components/SideBar.js
- frontend/src/pages/StatisticsPage/BarChart.js
- frontend/src/pages/StatisticsPage/StatisticsPage.js
통계 페이지 - 모바일 버전 추가
모바일 버전, 태블릿 버전 화면 크기에 맞게 두가지 버전 형태로 통계 페이지 구성
> feat: connection statistics chart

- frontend/public/assets/json/daily-menu/restaurant2.json
- frontend/src/App.js
- frontend/src/pages/NewPage/DeptTabMenu.js
- frontend/src/pages/NewPage/MenuItem.js
- frontend/src/pages/NewPage/NewPage.js
- frontend/src/pages/NewPage/ReviewForm.js
- frontend/src/pages/NewPage/TodayMenu.js
- frontend/src/redux/slice/MenuTypeSlice.js
- frontend/src/redux/slice/NowMenuSlice.js
- frontend/src/redux/store.js
새로운 메인페이지를 위한 오늘의 메뉴 보여주는 부분, 리뷰 작성하는 곳 제작
* 오늘의 메뉴는 아침, 점심, 저녁 등 여러 타입의 식사가 보일 수 있도록 
* 리뷰 작성하는 곳엔 메인 메뉴로 설정된 메뉴를 보일 수 있도록
> feat: new today menu and review write

- frontend/public/assets/json/review/restaurant2.json
- frontend/src/pages/ReviewPage/ReviewItem.js
- frontend/src/pages/ReviewPage/ReviewList.js
- frontend/src/pages/ReviewPage/ReviewSelect.js
리뷰 페이지 자체를 모두 개편을 하려고 했으나,
일단 리뷰 페이지를 잠시 막아두고, 메인 페이지에서만 리뷰를 사용하는 것으로 결정되어
ReviewItem만 사용하도록 한다.
> refactor: review page

- frontend/src/pages/NewPage/NewPage.js
- frontend/src/pages/NewPage/TodayMenu.js
- frontend/src/pages/NewPage/TopReview.js
- frontend/src/pages/ReviewPage/ReviewItem.js
> refactor: top review

- frontend/src/pages/MainPage/MainPage.js
- frontend/src/pages/MainPage/ReviewForm.js
- 메인 페이지 데이터가 준비되지 않을 시, 로딩 화면 게시
- 1학생회관에 대한 리뷰 작성 시, 백엔드 쪽에 메뉴 id가 넘어가지 않는 부분 해결
> 265 fix main page data loading and admin page

- frontend/src/pages/MainPage/MainPage.js
- frontend/src/pages/MainPage/TabBar.js
> fix: dept initialization

- frontend/src/pages/MyReviewPage/MyReviewItem.js
기존에 사용한 my review component 수정
> refactor: my review page

- frontend/src/pages/MainPage/ReviewForm.js
- frontend/src/pages/MainPage/TabBar.js
일관성을 위해 모바일인 경우, 아닌 경우 모두
버튼을 통해 원하는 학생 식당을 접근할 수 있도록 한다.
상황에 맞게 버튼이 사라지고, 나타난다.
- 모바일인 경우, 스크롤 하는 동작 제외
- 모바일이 아닌경우, 드래그 되는 동작 제외
> feat: tab bar moving button

- frontend/src/pages/MainPage/MainPage.js
- frontend/src/pages/MainPage/SwipeableTab.js
- frontend/src/pages/StatisticsPage/StatisticsPage.js
메인 페이지, 통계 페이지와 같이 학생식당 탭을 이용하는 곳에
swiper 기능 추가!
yarn add swiper
> 307 fix scrollable tab

- frontend/src/pages/MainPage/DeptTabMenu.js
- frontend/src/pages/MainPage/MainPage.js
- frontend/src/pages/MainPage/MenuItem.js
- frontend/src/pages/MainPage/SwipeableTab.js
- frontend/src/pages/MainPage/TodayMenu.js
- frontend/src/pages/MainPage/TypeTabMenu.js
- frontend/src/redux/slice/DeptSlice.js
- frontend/src/redux/slice/MenuTypeSlice.js
메인 페이지에서
식당 별 dept 선택 창을 type 선택 창으로 변경
> fix: change dept select to type select

- backend/src/main/java/com/SeeAndYouGo/SeeAndYouGo/menu/menuProvider/CrawlingMenuProvider.java
1. 아래와 같이 원산지가 줄바꿈 되었을 때, 원산지 앞까지 메뉴 저장하도록 수정.
돈육김치찌개[돈육:국내산
[배추:국내산,고추분:중국산]
2. 아래와 같은 메뉴가 나왔을 때 * 제거하고 표시.
*화이트데이 사탕*
3. 아래와 같이 원산지가 줄바꿈되어도 모두 무시하도록 수정.
[가쓰오-일본산
인도네이사산,필리핀산섞음]
> fix: way of crawling

- frontend/src/pages/MainPage/TodayMenu.js
- 학생식당에서 메인 메뉴가 있을때는 자동으로 선택이 됨
- 학생 식당, 교직원 식당이 있을때 학생 식단이 메인 메뉴가 설정되어 있지 않고 교직원 식당은 메인 메뉴가 있을때 교직원 식당은 자동으로 선택되지 않음. 
- 현재 선택된 dept에 메인 메뉴가 없을 경우, 다음으로 메인 메뉴가 있는 dept이 자동으로 선택되도록 변경
> fix: auto-select menu dept with available main menu

- frontend/src/pages/MainPage/Info.js
- frontend/src/pages/MainPage/MenuTableModal.js
- 주간메뉴 모달을 열 때마다 스크롤 위치가 항상 최상단으로 초기화되도록 수정
- 학생생활관을 제외한 모든 식당에서는 주말 메뉴가 표시되지 않도록 수정
> fix: reset weekly menu modal scroll and hide weekend menus

- frontend/src/App.js
- frontend/src/pages/AdminPage/SetDishNamePage.js
- frontend/src/pages/AdminPage/SetMainMenuPage.js
* dish 이름 편집 및 삭제 기능 추가
* main menu 페이지 1학 제외한 메뉴 보기 / 전체 메뉴 보기 기능을 넣어 기존 코드 수정
> 381 feat edit and delete dish name

- frontend/src/pages/MainPage/MenuItem.js
- 새로운 메뉴에 대한 하이라이트 표시 기능 추가
- N 표시에 마우스를 올리거나 모바일에선 터치하는 경우 tooltip이 잠깐 나타나도록 작성
(추후에..)
- 특정 메뉴에 대한 표시를 seeandyougo 고유 로고를 사용해
표현할 수 있는 기능을 추가할 예정
> feat: highlight new dish
